name = "sggweb"
main = ".output/server/index.mjs"
compatibility_date = "2024-01-01"

# Production environment
[env.production]
name = "sggweb-production"
route = "sggplay.com/*"
vars = { ENVIRONMENT = "production" }

# Production D1 database
[[env.production.d1_databases]]
binding = "DB"
database_name = "sgg-db"
database_id = "1a91d742-44d7-44ac-b3a3-5a01042abbf9"

# Production R2 bucket
[[env.production.r2_buckets]]
binding = "ASSETS"
bucket_name = "sgg-assets"

# Development environment
[env.dev]
name = "sggweb-dev"
route = "dev.sggplay.com/*"
vars = { ENVIRONMENT = "development" }

# Development D1 database
[[env.dev.d1_databases]]
binding = "DB"
database_name = "sgg-db-dev"
database_id = "b67c454e-a94f-4965-b4f1-8c5296483091"

# Development R2 bucket
[[env.dev.r2_buckets]]
binding = "ASSETS"
bucket_name = "sgg-assets-dev"
