name = "sggweb"
main = "@tanstack/react-start/server-entry"
compatibility_date = "2025-11-02"
compatibility_flags = ["nodejs_compat"]

# Production environment
[env.production]
name = "sggweb-production"
route = "sggplay.com/*"
vars = { ENVIRONMENT = "production" }

# Production D1 database
[[env.production.d1_databases]]
binding = "DB"
database_name = "sgg-db"
database_id = "1a91d742-44d7-44ac-b3a3-5a01042abbf9"

# Production R2 bucket
[[env.production.r2_buckets]]
binding = "R2_ASSETS"
bucket_name = "sgg-assets"

# Development environment
[env.dev]
name = "sggweb-dev"
vars = { ENVIRONMENT = "development" }
workers_dev = true

# Development D1 database
[[env.dev.d1_databases]]
binding = "DB"
database_name = "sgg-db-dev"
database_id = "b67c454e-a94f-4965-b4f1-8c5296483091"

# Development R2 bucket
[[env.dev.r2_buckets]]
binding = "R2_ASSETS"
bucket_name = "sgg-assets-dev"
